### ISSUE TITLE
Missing Implementation of EvalErrorMonad

### ISSUE THREAD

**Issue by marianpg** [lndrschlz/fpss17#1]
file: fpss17/08_arithmLogic/Data/Expr/ArithmLogic/EvalErrorMonad.hs
Please provide a proper implementation for that module, otherwise it is not possible to run your program. I really need it for my class.

With best regards!

**Comment by lndrschlz** [comment]
Dear @marianpg ,
the module you requested has been implemented and tested successfully. Please have in mind that the provided code comes without any warranty and is intended for educational purposes only.
Regards,
Leander
